name: Market Data Auto Update

on:
  schedule:
    - cron: '30 21 * * *'
    - cron: '30 5 * * *'
    - cron: '30 10 * * *'
    - cron: '30 16 * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Scraper API
        run: |
          curl -X POST https://market-backend-oozv.onrender.com/api/scrape/bim \
          -H "x-api-key: ${{ secrets.SCRAPER_API_KEY }}" \
          -H "Content-Type: application/json"
